package decotations;

public enum WeddingDecorationType {
    WEDDINGTABLECARDS,
    WEDDINGARCHROUND,
    WEDDINGARCHSQUARE,
    TABLECLOTH,
    CHAIRS,
    ROUNDTABLE,
    SQUARETABLE,
    CEREMONYTABLE,
    LISTBOXMIRROR,
    GLASSCANDLESTICKS,
    CANDLESTICKS,
    CANDLES,
    SMALLVASES,
    BIGVASES,
    FLOWERS,
    BALOONS,
    PLATES,
    HISANDHERSGLASSES,
    WINEGLASSES,
    SHOTGLASSES,
    WHISKEYGLASSES,
    CHAMPAGNEGLASSES,
    JUICEGLASSES,
    FORKS,
    SPOONS,
    TABLESPOONS,
    DESSERTSPOONS,
    KNIFES,
    NAPKINS

}
